project:
  type: website

website:
  title: "TLPortfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portfolio/lesson_plan.qmd
        text: "Lesson plan"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



