## Data Analysis and Bioinformatics

### Rmarkdown

Feb 13, 2023

#### Session overview

[One of the course learning outcomes was to design and teach a lesson plan.
I chose class and lesson plan because this is the type of class I can see myself
teaching and it was helpful to think about teaching others with a structure what I taught myself
in a less structured way]{.aside}

In this class, students will be introduced to rmarkdown. You will also learn
about the final project requirements and its submission format as an rmarkdown
report. The class will introduce markdown and its syntax, how rmarkdown extends
on markdown, and how to write an rmarkdown documents that can generate PDF,
HTML, and Word reports according to your requirements. We will learn how to
include reproducible code, analysis and results.

#### Learning outcomes

After this lesson, you will be able to

1. Create a new Rmarkdown file in RStudio and knit it to PDF, HTML, and Word
   documents.

2. Use R and bash code chunks to run statistical analyses and generate plots

3. Configure how code chunks and plots are knit to the final output document.

#### Resources

All resources for the lesson are on the class Github repository:

<https://github.com/Bioinformatics-Training-VAI/2023-data-sci-bioinfo/tree/rmarkdown/session5_rmarkdown>
[Only accessible for students in the class]{.aside}

There is a `example.rmd` which students will download for the practice parts of
class.

\newpage

### Lesson plan

[I overestimated some of the timings in the plan and the class finished much
earlier than thought it would. However, this meant students had time to work on
the homework and ask for help and troubleshooting while I was with them.]{.aside}

<table class="tg">
<thead>
  <tr>
    <th class="tg-ul38">Component</th>
    <th class="tg-ul38">Time (m)</th>
    <th class="tg-ul38">Description</th>
    <th class="tg-ul38">Resources</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax">Pre-class instructor tasks</td>
    <td class="tg-0lax">20</td>
    <td class="tg-0lax">Check with instructors on presenting the final project requirements</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax" rowspan="2">Pre-class requirements</td>
    <td class="tg-0lax">10</td>
    <td class="tg-0lax">Verify students have R, knitr, rmarkdown</td>
    <td class="tg-0lax" rowspan="2"><code>example.rmd</code> on github</td>
  </tr>
  <tr>
    <td class="tg-0lax">40</td>
    <td class="tg-0lax">Background reading</td>
  </tr>
  <tr>
    <td class="tg-0lax">Introduction: problem</td>
    <td class="tg-0lax">15</td>
    <td class="tg-0lax">Final project requirements: Dataset identification, report</td>
    <td class="tg-0lax">Course director / Github</td>
  </tr>
  <tr>
    <td class="tg-0lax">Lecture: Introduction to markdown</td>
    <td class="tg-0lax">10</td>
    <td class="tg-0lax">What is markdown and why use it? How can it help with student projects?
    [<br><br><br><br>To follow my problem solving as a learning goal principle,
    I tried to use the instructors description of the final project as the
    problem to be solved and the what they learn about Rmarkdown in class as the
    solution to that problem, with opportunities in class to simulate a final
    project.]{.aside}
    </td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">Recall and assessment/demo. Builds on git module</td>
    <td class="tg-0lax">5</td>
    <td class="tg-0lax">Have them run git diff on word docs to show why markdown is better for version control</td>
    <td class="tg-0lax"></td>
  <tr>
    <td class="tg-0lax">Practice</td>
    <td class="tg-0lax">15</td>
    <td class="tg-0lax">Have them open a sample and knit it, fixing any errors
    in <em>pairs</em></td>
    <td class="tg-0lax"><code>example.rmd</code> on github
    [<br><br><br>This would be a programming variant of think-pair-share
    where pair-programming helps students think about another persons problem
    and apply their knowledge in a slightly different situation. It also helps
    the person currently explaining their problem to have a moment of
    metacognition as they think about their learning and try to verbalize the
    problem they have.]{.aside}
    </td>
  </tr>
  <tr>
    <td class="tg-0lax">Lecture</td>
    <td class="tg-0lax">10</td>
    <td class="tg-0lax">Knitting to different output formats</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">Practice and demo themes</td>
    <td class="tg-0lax">20</td>
    <td class="tg-0lax">Use the sample to knit to HTML, word, and pdf with different options</td>
    <td class="tg-0lax"><code>example.rmd</code> on github</td>
  </tr>
  <tr>
    <td class="tg-0lax">Break</td>
    <td class="tg-0lax">5</td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">Follow-along code demo</td>
    <td class="tg-0lax">20</td>
    <td class="tg-0lax">Code and chunk options</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">Practice and formative assessment</td>
    <td class="tg-0lax">15</td>
    <td class="tg-0lax">Take the iris dataset, run an ANOVA, make plots with captions, verify that it knits, submit markdown on github</td>
    <td class="tg-0lax"><code>example.rmd</code> on github</td>
  </tr>
  <tr>
    <td class="tg-0lax">Demo</td>
    <td class="tg-0lax">10</td>
    <td class="tg-0lax">Tour of RStudio and its config options that help with writing and editing</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">Homework and next steps</td>
    <td class="tg-0lax">5</td>
    <td class="tg-0lax">If they haven't finished the formative assessment, they can do it over the next week and submit to github</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">Post-class tasks: instructor</td>
    <td class="tg-0lax">20</td>
    <td class="tg-0lax">Check in with students who had trouble to make sure they
    have what they need to complete the work</td>
    <td class="tg-0lax"></td>
  </tr>
</tbody>
</table>


#### Context and relevance

This lesson is part of the Data Analysis and Bioinformatics class at VAIGS. The
course goal is to introduce first-year PhD students to common bioinformatic
tools and teach them how to use them during in their work. Before this lesson,
students would have learned how to navigate a linux filesystem and manipulate
files, use git and github to share and version control files, and use R for
basic data input and statistical analysis. For this lesson, students will need
to remember the R code they learned in the previous two lessons. During this
lesson they will learn how the analysis done with those methods can be
integrated into one shareable, version controlled report that includes both
their code and their analysis. Subsequent lessons will have more involved
analyses that would require students to maintain reproducible reports using
Rmarkdown and the course will end with them presenting their project as the
output of an Rmarkdown document with properly formatted code and results.

#### Pre-teaching reflection

During this lesson, the hardest thing for students to work with would be the
move from writing prose in a what-you-see-is-what-you-get editor to one where
they have to set formatting and layout using symbols and code. There are also a
lot of configuration options that may overwhelm them. As an instructor, I would
need to make sure they are all on the same page, and work with any problems that
might result from differences in the laptops they have or their prior skillset.
I would also have to make sure they understand the configuration options they
need, but also let them know that although there are a lot of options, they
don't need to know or understand all of them in this lesson. They can be
confident that what they learn here can be useful to them and help them learn
more.

#### Post-teaching reflection

The course instructors introduced the final project requirements - which is the
summative assessment for the class. However, they did it a little differently
than I expected from my time in the class and did not go into a lot of detail on
the datasets required or the final presentation format. I tried to incorporate a
bit of that in my introduction.

The introduction went well, but the first practice/test of their ability to run
the code did not go smoothly since there were differences in their computer
hardware and R installations that gave some trouble. It was also clear that not
everyone had done the pre-class assignment fully. This did not take too long
since I was able to give them alternative ways to follow along in class.

During the class, some of the students showed that they had some experience with
the subject and had informed questions, while others were very quiet, even when
asked whether they had caught up to what I had asked them to do.

I had an hour at the end where they were working on their formative assessment.
The goal was to get them to practice working with Markdown and generate a
short, but full report on a small dataset. I'm glad I had the full time, since
there was a wider range of skill than I expected and this allowed me to walk
around the class as they worked and help as needed. There were some students who
asked for help only as I came around. The slower students were able to ask for
help to complete the work, while the faster ones completed the work and had time
to explore other configuration options for their reports.

I think I could have broken down the material and added more to make it more
granular - they did not know some things I thought they would. Some of it was
outside my control and from the previous classes that I only knew the title of -
I didn't attend the class and see exactly what they learned and how proficient
they got. It seemed like they learned some things, but did not have much time to
practice them.
